### ISSUE TITLE
Questions about the generating gray depth

### ISSUE THREAD

**Issue by zhangtingyu11** [YufeiWang777/LRRU#10]
Hello, thank you for sharing this incredible work. I am new to depth completion, and I would like to utilize the depth completion results for KITTI 3D object detection images. I'm currently facing some challenges, and I was wondering if you could help me with a few questions regarding the generation process. The yml file has been modified as follows.
```yml
# Hardware
seed: 1128
gpus: (0, )
port: 29000
num_threads: 1
no_multiprocessing: True
cudnn_deterministic: False
cudnn_benchmark: True

# Dataset
data_folder: '/home/public/zty/Project/DeepLearningProject/LRRU/kitti/training'
dataset: ['dep', 'gt', 'rgb']
val: 'test_completion'
grid_spot: True
num_sample: 1000
cut_mask: False
max_depth: 80.0
rgb_noise: 0.0
noise: 0.0

hflip: True
colorjitter: True
rotation: True
resize: False
normalize: True
scale_depth: False

val_h: 352
val_w: 1216
random_crop_height: 256
random_crop_width: 1216
train_bottom_crop: True
train_random_crop: True
val_bottom_crop: True
val_random_crop: True
test_bottom_crop: True
test_random_crop: True

# Network
depth_norm: False
dkn_residual: True
summary_name: 'summary'

# Test
test: True
#test_option: 'test_completion'
test_option: 'test_completion'
test_name: 'ben_depth'
tta: False
test_not_random_crop: True
wandb_id_test: ''

prob: 0.5
bc: 16
model: 'model_dcnv2'
test_dir: './pretrained/LRRU_Base'
test_model: './pretrained/LRRU_Base/LRRU_Base.pt'

# Summary
num_summary: 6
save_test_image: True

# Logs
vis_step: 1000
record_by_wandb_online: False
test_record_by_wandb_online: False
save_result_only: False
```
1. When running` val.py` based on the provided yml file, I can generate an RGB depth map. If I aim to obtain a grayscale depth map similar to the depth completion dataset, I am wondering whether sample['dep'] represents the absolute depth. To clarify, is sample['dep'] the absolute depth, or does it require a transformation to obtain the absolute depth?
https://github.com/YufeiWang777/LRRU/blob/02be555f3a5046f4441eafa782194fbd31dbdca0/summary/summary.py#L164-L166

2. Noticing that the output feature size is 1216 * 256, matching the `random_crop_height` and `random_crop_width` parameters, I observe that depth maps from other methods are 1216 * 352. How can I obtain a depth map of size 1216 * 352, and does the resizing operation affect performance?

3. In the KITTI raw dataset, the intrinsic matrix is 3\*3, whereas in 3D object detection, the calib file contains P2, a 3\*4 matrix (assumed to be the projection matrix). How can I extract the intrinsic matrix from the projection matrix?

Thanks in advance!
